# Publishing via JitPack
# JitPack builds are triggered automatically from git tags/releases.
# To publish a new version:
# 1. Create a git tag: git tag -a v6.7.0-4 -m "Release v6.7.0-4"
# 2. Push the tag: git push origin v6.7.0-4
# 3. JitPack will build on-demand when users request the version
#
# Users can then add to their build.gradle:
# repositories {
#     maven { url 'https://jitpack.io' }
# }
# dependencies {
#     implementation 'com.github.PAIR-Systems-Inc:javalin-openapi:v6.7.0-4'
# }

name: "Build Verification"
on:
  push:
    branches: [ "main" ]

env:
  JAVA_VERSION: 17

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Set up Java ${{ env.JAVA_VERSION }}"
        uses: actions/setup-java@v3
        with:
          java-version: "${{ env.JAVA_VERSION }}"
          distribution: "adopt"

      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew

      - name: "Gradle build"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: "clean build"
